### ISSUE TITLE
如下图，点击登录后跳转的页面。 已经无法登录了，请作者维护一下，尽快恢复？谢谢。

### ISSUE THREAD

**Issue by iamaaronhu** [rowthan/developer.pagenote.cn#13]
![image](https://user-images.githubusercontent.com/96708393/233592070-926dad0b-f1fc-4c41-a11b-c612c3038544.png)

![image](https://user-images.githubusercontent.com/96708393/233592132-3199a0a7-70b0-4f94-ab56-e29e568c5d06.png)
如下图，点击登录后跳转的页面。 已经无法登录了，请作者维护一下，尽快恢复？谢谢。

**Comment by rowthan** [comment]
请更新至0.26.5以上版本
