### ISSUE TITLE
 TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by Dook1** [rowthan/developer.pagenote.cn#47]
TypeError: document.querySelector(...) is null
    getWebKeywords moz-extension://d3faeb35-8349-44e4-ae9c-2fca681120cb/rollup/inject_check.js:1
    fetchStatus moz-extension://d3faeb35-8349-44e4-ae9c-2fca681120cb/rollup/inject_check.js:2
    <anonymous> moz-extension://d3faeb35-8349-44e4-ae9c-2fca681120cb/rollup/inject_check.js:2
    startListen moz-extension://d3faeb35-8349-44e4-ae9c-2fca681120cb/rollup/inject_check.js:1

v0.27.1.1

**Comment by Dook1** [comment]
v0.27.3 
same problem

**Comment by rowthan** [comment]
solved in v0.27.4

**Comment by Dook1** [comment]
When will v0.27.4 be available for download from addons.mozilla.org?

**Comment by rowthan** [comment]
> When will v0.27.4 be available for download from addons.mozilla.org?

available now

**Comment by Dook1** [comment]
thanks
